// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/main.proto

package infosvc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WhatIsGithubRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhatIsGithubRequest) Reset()         { *m = WhatIsGithubRequest{} }
func (m *WhatIsGithubRequest) String() string { return proto.CompactTextString(m) }
func (*WhatIsGithubRequest) ProtoMessage()    {}
func (*WhatIsGithubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{0}
}

func (m *WhatIsGithubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhatIsGithubRequest.Unmarshal(m, b)
}
func (m *WhatIsGithubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhatIsGithubRequest.Marshal(b, m, deterministic)
}
func (m *WhatIsGithubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhatIsGithubRequest.Merge(m, src)
}
func (m *WhatIsGithubRequest) XXX_Size() int {
	return xxx_messageInfo_WhatIsGithubRequest.Size(m)
}
func (m *WhatIsGithubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhatIsGithubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhatIsGithubRequest proto.InternalMessageInfo

type WhatIsGithubResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhatIsGithubResponse) Reset()         { *m = WhatIsGithubResponse{} }
func (m *WhatIsGithubResponse) String() string { return proto.CompactTextString(m) }
func (*WhatIsGithubResponse) ProtoMessage()    {}
func (*WhatIsGithubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{1}
}

func (m *WhatIsGithubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhatIsGithubResponse.Unmarshal(m, b)
}
func (m *WhatIsGithubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhatIsGithubResponse.Marshal(b, m, deterministic)
}
func (m *WhatIsGithubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhatIsGithubResponse.Merge(m, src)
}
func (m *WhatIsGithubResponse) XXX_Size() int {
	return xxx_messageInfo_WhatIsGithubResponse.Size(m)
}
func (m *WhatIsGithubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhatIsGithubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhatIsGithubResponse proto.InternalMessageInfo

func (m *WhatIsGithubResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type WhoAmIRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhoAmIRequest) Reset()         { *m = WhoAmIRequest{} }
func (m *WhoAmIRequest) String() string { return proto.CompactTextString(m) }
func (*WhoAmIRequest) ProtoMessage()    {}
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{2}
}

func (m *WhoAmIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhoAmIRequest.Unmarshal(m, b)
}
func (m *WhoAmIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhoAmIRequest.Marshal(b, m, deterministic)
}
func (m *WhoAmIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhoAmIRequest.Merge(m, src)
}
func (m *WhoAmIRequest) XXX_Size() int {
	return xxx_messageInfo_WhoAmIRequest.Size(m)
}
func (m *WhoAmIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhoAmIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhoAmIRequest proto.InternalMessageInfo

type WhoAmIResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhoAmIResponse) Reset()         { *m = WhoAmIResponse{} }
func (m *WhoAmIResponse) String() string { return proto.CompactTextString(m) }
func (*WhoAmIResponse) ProtoMessage()    {}
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{3}
}

func (m *WhoAmIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhoAmIResponse.Unmarshal(m, b)
}
func (m *WhoAmIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhoAmIResponse.Marshal(b, m, deterministic)
}
func (m *WhoAmIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhoAmIResponse.Merge(m, src)
}
func (m *WhoAmIResponse) XXX_Size() int {
	return xxx_messageInfo_WhoAmIResponse.Size(m)
}
func (m *WhoAmIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhoAmIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhoAmIResponse proto.InternalMessageInfo

func (m *WhoAmIResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*WhatIsGithubRequest)(nil), "info.WhatIsGithubRequest")
	proto.RegisterType((*WhatIsGithubResponse)(nil), "info.WhatIsGithubResponse")
	proto.RegisterType((*WhoAmIRequest)(nil), "info.WhoAmIRequest")
	proto.RegisterType((*WhoAmIResponse)(nil), "info.WhoAmIResponse")
}

func init() { proto.RegisterFile("proto/main.proto", fileDescriptor_098391ad7281b52b) }

var fileDescriptor_098391ad7281b52b = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x03, 0x33, 0x85, 0x58, 0x32, 0xf3, 0xd2, 0xf2, 0x95,
	0x44, 0xb9, 0x84, 0xc3, 0x33, 0x12, 0x4b, 0x3c, 0x8b, 0xdd, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xb4, 0xb8, 0x44, 0x50, 0x85, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x25, 0x7e, 0x2e, 0xde, 0xf0, 0x8c, 0x7c, 0xc7, 0x5c, 0x4f, 0x98, 0x66, 0x1d,
	0x2e, 0x3e, 0x98, 0x00, 0x54, 0x9b, 0x14, 0x17, 0x47, 0x69, 0x71, 0x6a, 0x51, 0x5e, 0x62, 0x6e,
	0x2a, 0x54, 0x2b, 0x9c, 0x6f, 0xd4, 0xc9, 0xc8, 0xc5, 0xee, 0x99, 0x97, 0x96, 0x1f, 0x5c, 0x96,
	0x2c, 0xe4, 0xce, 0xc5, 0x83, 0x6c, 0xad, 0x90, 0xa4, 0x1e, 0xc8, 0x91, 0x7a, 0x58, 0x5c, 0x28,
	0x25, 0x85, 0x4d, 0x0a, 0x62, 0x9d, 0x12, 0x83, 0x90, 0x29, 0x17, 0x1b, 0xc4, 0x09, 0x42, 0xc2,
	0x30, 0x75, 0x48, 0x2e, 0x94, 0x12, 0x41, 0x15, 0x84, 0x69, 0x73, 0x32, 0x88, 0xd2, 0x4b, 0x07,
	0x1b, 0xa5, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x58, 0x54, 0x90, 0x59, 0x92, 0x94, 0x94, 0x91, 0x58,
	0x99, 0x98, 0x97, 0xa9, 0x9f, 0x5e, 0x54, 0x90, 0xac, 0x9b, 0x99, 0xa7, 0x9b, 0x92, 0x5a, 0x50,
	0x92, 0xa1, 0x0f, 0xd2, 0x5f, 0x5c, 0x96, 0x9c, 0xc4, 0x06, 0x0e, 0x4c, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x4f, 0x0b, 0xd7, 0x94, 0x60, 0x01, 0x00, 0x00,
}
