// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/main.proto

package infosvc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WhatIsGithubRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhatIsGithubRequest) Reset()         { *m = WhatIsGithubRequest{} }
func (m *WhatIsGithubRequest) String() string { return proto.CompactTextString(m) }
func (*WhatIsGithubRequest) ProtoMessage()    {}
func (*WhatIsGithubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{0}
}

func (m *WhatIsGithubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhatIsGithubRequest.Unmarshal(m, b)
}
func (m *WhatIsGithubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhatIsGithubRequest.Marshal(b, m, deterministic)
}
func (m *WhatIsGithubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhatIsGithubRequest.Merge(m, src)
}
func (m *WhatIsGithubRequest) XXX_Size() int {
	return xxx_messageInfo_WhatIsGithubRequest.Size(m)
}
func (m *WhatIsGithubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhatIsGithubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhatIsGithubRequest proto.InternalMessageInfo

type WhatIsGithubResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhatIsGithubResponse) Reset()         { *m = WhatIsGithubResponse{} }
func (m *WhatIsGithubResponse) String() string { return proto.CompactTextString(m) }
func (*WhatIsGithubResponse) ProtoMessage()    {}
func (*WhatIsGithubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{1}
}

func (m *WhatIsGithubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhatIsGithubResponse.Unmarshal(m, b)
}
func (m *WhatIsGithubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhatIsGithubResponse.Marshal(b, m, deterministic)
}
func (m *WhatIsGithubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhatIsGithubResponse.Merge(m, src)
}
func (m *WhatIsGithubResponse) XXX_Size() int {
	return xxx_messageInfo_WhatIsGithubResponse.Size(m)
}
func (m *WhatIsGithubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhatIsGithubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhatIsGithubResponse proto.InternalMessageInfo

func (m *WhatIsGithubResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*WhatIsGithubRequest)(nil), "info.WhatIsGithubRequest")
	proto.RegisterType((*WhatIsGithubResponse)(nil), "info.WhatIsGithubResponse")
}

func init() { proto.RegisterFile("proto/main.proto", fileDescriptor_098391ad7281b52b) }

var fileDescriptor_098391ad7281b52b = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x03, 0x33, 0x85, 0x58, 0x32, 0xf3, 0xd2, 0xf2, 0x95,
	0x44, 0xb9, 0x84, 0xc3, 0x33, 0x12, 0x4b, 0x3c, 0x8b, 0xdd, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xb4, 0xb8, 0x44, 0x50, 0x85, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0xa3, 0x20, 0x2e, 0x76, 0xcf, 0xbc, 0xb4, 0xfc, 0xe0, 0xb2, 0x64, 0x21, 0x77,
	0x2e, 0x1e, 0x64, 0x6d, 0x42, 0x92, 0x7a, 0x20, 0x4b, 0xf4, 0xb0, 0xd8, 0x20, 0x25, 0x85, 0x4d,
	0x0a, 0x62, 0x8b, 0x12, 0x83, 0x93, 0x41, 0x94, 0x5e, 0x3a, 0x58, 0x4c, 0x2f, 0x39, 0x3f, 0x57,
	0x3f, 0xb1, 0xa8, 0x20, 0xb3, 0x24, 0x29, 0x29, 0x23, 0xb1, 0x32, 0x31, 0x2f, 0x53, 0x3f, 0xbd,
	0xa8, 0x20, 0x59, 0x37, 0x33, 0x4f, 0x37, 0x25, 0xb5, 0xa0, 0x24, 0x43, 0x1f, 0x64, 0x4a, 0x71,
	0x59, 0x72, 0x12, 0x1b, 0xd8, 0x57, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0x26, 0xf1,
	0x64, 0xe9, 0x00, 0x00, 0x00,
}
